---
# Source: erpnext/templates/job-configure-bench.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: frappe-bench-erpnext-conf-bench-20251004020237
  labels:
    helm.sh/chart: erpnext-7.0.239
    app.kubernetes.io/name: erpnext
    app.kubernetes.io/instance: frappe-bench
    app.kubernetes.io/version: "v15.81.1"
    app.kubernetes.io/managed-by: Helm
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: frappe-bench-erpnext
      initContainers:
      - name: frappe-bench-ownership
        image: frappe/erpnext:v15.81.1
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args:
          - chown -R "1000:1000" /home/frappe/frappe-bench/sites /home/frappe/frappe-bench/logs
        resources:
          {}
        securityContext:
          # run as root to set ownership
          runAsUser: 0
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      securityContext:
        supplementalGroups:
        - 1000
      containers:
      - name: configure
        image: "frappe/erpnext:v15.81.1"
        imagePullPolicy: IfNotPresent
        command:
          - bash
          - -c
        args:
          - >
            ls -1 apps > sites/apps.txt;
            [[ -f sites/common_site_config.json ]] || echo "{}" > sites/common_site_config.json;
            bench set-config -gp db_port $DB_PORT;
            bench set-config -g db_host $DB_HOST;
            bench set-config -g redis_cache $REDIS_CACHE;
            bench set-config -g redis_queue $REDIS_QUEUE;
            bench set-config -g redis_socketio $REDIS_QUEUE;
            bench set-config -gp socketio_port $SOCKETIO_PORT;
        env:
          - name: DB_HOST
            value: mariadb-galera.db.svc.cluster.local
          - name: DB_PORT
            value: "3306"
          - name: REDIS_CACHE
            value: redis://frappe-bench-redis-cache-master:6379
          - name: REDIS_QUEUE
            value: redis://frappe-bench-redis-queue-master:6379
          - name: SOCKETIO_PORT
            value: "9000"
        resources:
          {}
        volumeMounts:
          - name: sites-dir
            mountPath: /home/frappe/frappe-bench/sites
          - name: logs
            mountPath: /home/frappe/frappe-bench/logs
      restartPolicy: Never
      volumes:
        - name: sites-dir
          persistentVolumeClaim:
            claimName: frappe-bench-erpnext
            readOnly: false
        - name: logs
          emptyDir: {}
