# galera-values.yaml
replicaCount: 3

image:
  registry: docker.io
  repository: bitnamilegacy/mariadb-galera
  tag: 10.6.16

# App credentials (CHANGE THESE!)
rootUser:
  password: "petalErpSafe47"
db:
  user: "erpnext"
  password: "petalErpSafe47"
  name: "erpnext"

galera:
  bootstrap:
    # -- Node to bootstrap from, you will need to change this parameter in case you want to bootstrap from other node
    bootstrapFromNode: "2"
    # -- Force `safe_to_bootstrap: 1` in `grastate.date` file.
    # This will set safe_to_bootstrap=1 in the node indicated by bootstrapFromNode.
    forceSafeToBootstrap: false
  mariabackup:
    password: "petalErpSafe47"

persistence:
  enabled: true
  size: 10Gi            # keep small; you can grow later
  storageClass: oci-bv  # RWO Block Volume on OKE Basic

# Keep resource use minimal (dev-fit)
resources:
  requests:
    cpu: "500m"
    memory: "1500Mi"
  limits:
    cpu: "3"
    memory: "2500Mi"
    

livenessProbe:
  enabled: true
  initialDelaySeconds: 300
  periodSeconds: 30
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 15
  timeoutSeconds: 10
  failureThreshold: 5    
    
mariadbConfiguration: |-
  [client]
  port=3306
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  plugin_dir=/opt/bitnami/mariadb/plugin
  default-character-set = utf8mb4

  [mysqld]
  default_storage_engine=InnoDB
  basedir=/opt/bitnami/mariadb
  datadir=/bitnami/mariadb/data
  plugin_dir=/opt/bitnami/mariadb/plugin
  tmpdir=/opt/bitnami/mariadb/tmp
  socket=/opt/bitnami/mariadb/tmp/mysql.sock
  pid_file=/opt/bitnami/mariadb/tmp/mysqld.pid
  bind_address=0.0.0.0

  ## Character set
  character-set-client-handshake = FALSE
  character-set-server = utf8mb4
  collation-server = utf8mb4_unicode_ci
  init_connect='SET NAMES utf8mb4'

  ## MyISAM
  key_buffer_size=32M
  myisam_recover_options=FORCE,BACKUP

  ## Safety
  skip_host_cache
  skip_name_resolve
  max_allowed_packet=16M
  max_connect_errors=1000000
  sql_mode=STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_AUTO_VALUE_ON_ZERO,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE
  sysdate_is_now=1

  ## Binary Logging
  log_bin=mysql-bin
  expire_logs_days=14
  sync_binlog=0
  binlog_format=row

  ## Caches and Limits
  tmp_table_size=32M
  max_heap_table_size=32M
  query_cache_type=1
  query_cache_limit=4M
  query_cache_size=256M
  max_connections=500
  thread_cache_size=50
  open_files_limit=65535
  table_definition_cache=4096
  table_open_cache=4096

  ## InnoDB
  innodb=FORCE
  innodb_strict_mode=1
  innodb_autoinc_lock_mode=2
  innodb_doublewrite=1
  innodb_flush_method=O_DIRECT
  innodb_log_files_in_group=2
  innodb_log_file_size=128M
  innodb_flush_log_at_trx_commit=1
  innodb_file_per_table=1
  innodb_buffer_pool_size=2G
  innodb_file_format=Barracuda

  ## Logging
  log_error=/opt/bitnami/mariadb/logs/mysqld.log
  slow_query_log_file=/opt/bitnami/mariadb/logs/mysqld.log
  log_queries_not_using_indexes=1
  slow_query_log=1

  [galera]
  wsrep_on=ON
  wsrep_provider=/opt/bitnami/mariadb/lib/libgalera_smm.so
  wsrep_sst_method=mariabackup
  wsrep_slave_threads=4
  wsrep_cluster_address=gcomm://
  wsrep_cluster_name=galera
  wsrep_sst_auth="root:"
  innodb_flush_log_at_trx_commit=2
  wsrep_replicate_myisam=ON

  [mariadb]
  plugin_load_add=auth_pam

  [mysql]
  default-character-set = utf8mb4


# Minimal InnoDB + connections for 6GB nodes
configuration: |
  [mysqld]
  character-set-client-handshake = FALSE
  character-set-server = utf8mb4
  collation-server = utf8mb4_unicode_ci

  innodb_buffer_pool_size=1G
  innodb_log_file_size=256M
  max_connections=150
  query_cache_type=0
  thread_cache_size=64
  table_open_cache=2048
  log_bin=binlog
  binlog_format=ROW
  sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
  # Galera basics (chart wires wsrep_cluster_address automatically)
  wsrep_slave_threads=2
  wsrep_provider_options="gcache.size=512M"

  [mysql]
  default-character-set = utf8mb4

# Spread pods; avoid piling onto one node
podAntiAffinityPreset: soft
